eureka:

  client:

    register-with-eureka: true

    fetch-registry: true

    service-url:

      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/

  instance:

    prefer-ip-address: true

    hostname: localhost

 
 
management:

  tracing:

    sampling:

      probability: 1.0

  zipkin:

    tracing:

      endpoint: http://localhost:9411     

server:

  port: 1010

spring:

  application:

    name: OLX-Login

  config:

    import:

    - configserver:http://localhost:8888
 
  data:

    mongodb:

      database: olx_user

      host: localhost

      port: 27017

  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver

    password: root

    url: jdbc:mysql://localhost:3306/olx_users

    username: root

  jpa:

    hibernate:

      ddl-auto: update

    properties:

      hibernate:

        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:

  show-actuator: 'TRUE'
 
server:

  port: 9081

eureka:

  client:

    register-with-eureka: true

    fetch-registry: true

    service-url:

      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/

  instance:

    prefer-ip-address: true

    hostname: localhost

spring:

  application:

    name: OLX-MasterData

  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver

    password: root

    url: jdbc:mysql://localhost:3306/olx_masterdata

    username: root

  jpa:

    hibernate:

      ddl-auto: update

    properties:

      hibernate:

        dialect: org.hibernate.dialect.MySQL8Dialect


management:

  tracing:

    sampling:

      probability: 1.0

  zipkin:

    tracing:

      endpoint: http://localhost:9411     

springdoc:

  show-actuator: 'TRUE'
 
 
